import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { Resend } from 'resend';
import { UserRepository } from '../../entities/repository/user.repository';
import { ChurchRepository } from '../../entities/repository/church.repository';
import { getTranslation } from './i18n/translations';

@Injectable()
export class EmailService {
  private readonly logger = new Logger(EmailService.name);
  private resend: Resend | null = null;
  private readonly isDevelopment: boolean;
  private readonly fromEmail: string;

  // Resend Template IDs (configured in Resend dashboard)
  private readonly TEMPLATE_IDS = {
    welcome: 'b2d18ce4-ee87-47d8-bde1-31b62583b903',
    resetPassword: '3f4a4e81-cd0c-4260-b7fc-c0f2d121ed30',
    paymentError: '510273e8-1fd8-4e4f-9b85-1c66306cf3aa'
  };

  constructor(
    private readonly configService: ConfigService,
    private readonly userRepository: UserRepository,
    private readonly churchRepository: ChurchRepository,
  ) {
    this.isDevelopment = this.configService.get<string>('ENV') === 'development';
    
    const apiKey = this.configService.get<string>('RESEND_API_KEY');
    this.fromEmail = this.configService.get<string>('RESEND_FROM_EMAIL') || 
                     'noreply@oliva.church';
    
    if (!apiKey) {
      this.logger.warn('RESEND_API_KEY not configured. Email service will be disabled.');
      return;
    }
    
    try {
      this.resend = new Resend(apiKey);
      this.logger.log('✓ Resend email service initialized');
    } catch (error) {
      this.logger.error('Failed to initialize Resend:', error.message);
    }
  }



  /**
   * Send password reset email to user
   * @param email User email address
   * @param resetToken Secure reset token generated by AuthService
   * @param resetUrl Full reset URL with token
   * @returns Promise<boolean> Success status
   */
  async sendPasswordReset(
    email: string,
    resetToken: string,
    resetUrl: string,
  ): Promise<boolean> {
    try {
      if (!this.resend) {
        this.logger.error('Resend not initialized. Cannot send password reset email.');
        return false;
      }

      // Find user by email (without leaking user existence info)
      const user = await this.userRepository.findOne({ 
        where: { email },
        relations: ['church'],
      });
      
      if (!user) {
        // Don't reveal if user exists - log internally but return success to client
        this.logger.warn(`Password reset requested for non-existent email (not logged): ${this.maskEmail(email)}`);
        return true; // Security: Don't leak user existence
      }

      // Get church preferred language
      const language = user.church?.preferredLanguage || 'pt';
      const t = getTranslation(language).resetPassword;

      const subject = this.isDevelopment
        ? `[DEV] ${t.subject}`
        : t.subject;

      const { data, error } = await this.resend.emails.send({
        from: `Oliva <${this.fromEmail}>`,
        to: [email],
        subject,
        template: {
          id: this.TEMPLATE_IDS.resetPassword,
          variables: {
            ...t,
            resetUrl,
            resetToken,
            minutesValid: 60
          }
        }
      });


      if (error) {
        this.logger.error(
          `Failed to send password reset email to ${this.maskEmail(email)}: ${error.message}`,
        );
        return false;
      }

      this.logger.log(
        `Password reset email sent successfully to ${this.maskEmail(email)}. MessageId: ${data.id}`,
      );

      return true;
    } catch (error) {
      this.logger.error(
        `Failed to send password reset email to ${this.maskEmail(email)}`,
        error.stack,
      );
      return false;
    }
  }

  /**
   * Send welcome email to new user
   * @param email User email address
   * @param userName User full name
   * @param churchName Church name
   * @returns Promise<boolean> Success status
   */
  async sendWelcomeEmail(
    email: string,
    userName: string,
    churchName: string,
    churchId?: string,
  ): Promise<boolean> {
    try {
      if (!this.resend) {
        this.logger.error('Resend not initialized. Cannot send welcome email.');
        return false;
      }

      // Get church preferred language
      let language = 'pt';
      if (churchId) {
        const church = await this.churchRepository.findOne({ where: { id: churchId } });
        language = church?.preferredLanguage || 'pt';
      }
      
      const t = getTranslation(language).welcome;
      const frontendUrl = this.configService.get<string>('FRONTEND_URL') || 'https://oliva.church';

      const subject = this.isDevelopment
        ? `[DEV] ${t.subject}`
        : t.subject;

      const { data, error } = await this.resend.emails.send({
        from: `Oliva <${this.fromEmail}>`,
        to: [email],
        subject,
        template: {
          id: this.TEMPLATE_IDS.welcome,
          variables: {
            ...t,
            userName,
            churchName,
            churchId: churchId || '',
            frontendUrl
          }
        }
      });

      if (error) {
        this.logger.error(
          `Failed to send welcome email to ${this.maskEmail(email)}: ${error.message}`,
        );
        return false;
      }

      this.logger.log(
        `Welcome email sent successfully to ${this.maskEmail(email)}. MessageId: ${data.id}`,
      );

      return true;
    } catch (error) {
      this.logger.error(
        `Failed to send welcome email to ${this.maskEmail(email)}`,
        error.stack,
      );
      return false;
    }
  }

  /**
   * Send payment failure notification email to admin
   * @param churchId Church ID
   * @returns Promise<boolean> Success status
   */
  async sendPaymentFailedEmail(churchId: string): Promise<boolean> {
    try {
      if (!this.resend) {
        this.logger.error('Resend not initialized. Cannot send payment failed email.');
        return false;
      }

      // Find church and admin user
      const church = await this.churchRepository.findOne({
        where: { id: churchId },
        relations: ['users'],
      });

      if (!church) {
        this.logger.error(`Church not found: ${churchId}`);
        return false;
      }

      // Find admin user
      const adminUser = await this.userRepository.findOne({
        where: { churchId, role: { slug: 'ADMIN' } } as any,
        relations: ['members', 'role'],
      });

      if (!adminUser) {
        this.logger.error(`Admin user not found for church: ${churchId}`);
        return false;
      }

      // Get admin name from first member or use default
      const adminName = adminUser.members && adminUser.members.length > 0 
        ? adminUser.members[0].name 
        : 'Administrador';

      // Get church preferred language
      const language = church.preferredLanguage || 'pt';
      const t = getTranslation(language).paymentFailed;

      // Build dashboard URL
      const frontendUrl = this.configService.get<string>('FRONTEND_URL') || 'https://oliva.church';
      const dashboardUrl = `${frontendUrl}/settings/subscription`;

      const subject = this.isDevelopment
        ? `[DEV] ${t.subject}`
        : t.subject;

      const { data, error } = await this.resend.emails.send({
        from: `Oliva <${this.fromEmail}>`,
        to: [adminUser.email],
        subject,
        template: {
          id: this.TEMPLATE_IDS.paymentError,
          variables: {
            ...t,
            adminName,
            churchName: church.name,
            churchId,
            dashboardUrl,
            frontendUrl
          }
        }
      });

      if (error) {
        this.logger.error(
          `Failed to send payment failed email to ${this.maskEmail(adminUser.email)}: ${error.message}`,
        );
        return false;
      }

      this.logger.log(
        `Payment failed email sent successfully to ${this.maskEmail(adminUser.email)} for church ${church.name}. MessageId: ${data.id}`,
      );

      return true;
    } catch (error) {
      this.logger.error(
        `Failed to send payment failed email for church ${churchId}`,
        error.stack,
      );
      return false;
    }
  }

  /**
   * Mask email address for logging (security best practice)
   * Example: john.doe@example.com -> j***e@e***.com
   */
  private maskEmail(email: string): string {
    if (!email || !email.includes('@')) return '***';
    
    const [localPart, domain] = email.split('@');
    const maskedLocal = localPart.length > 2
      ? `${localPart[0]}***${localPart[localPart.length - 1]}`
      : '***';
    
    const [domainName, tld] = domain.split('.');
    const maskedDomain = domainName.length > 2
      ? `${domainName[0]}***`
      : '***';
    
    return `${maskedLocal}@${maskedDomain}.${tld}`;
  }

  /**
   * Health check method for monitoring
   */
  async isHealthy(): Promise<boolean> {
    return !!this.resend;
  }
}
